#![allow(
    clippy::decimal_bitwise_operands,
    clippy::suboptimal_flops,
    reason = "seed xor constants and layered noise formulas are clearer in their authored form"
)]

use crate::{
    GeneratedTexture, TextureColorSpace, TextureSize,
    builders::{build_albedo, build_normal, build_orm},
    noise::{fbm, hairline, speckle},
};

use super::params::PlasterParams;

/// PBR channel generated by the plaster texture pipeline.
/// Note: it's ok to keep it Copy, since it's just a numeric enum
#[derive(Debug, Clone, Copy, Eq, PartialEq, Hash)]
pub enum TextureKind {
    /// Base color texture.
    Albedo,
    /// Tangent-space normal map.
    Normal,
    /// Occlusion, roughness, metallic packed texture.
    Orm,
}

impl TextureKind {
    /// Human-readable channel label for UI and logs.
    #[must_use]
    pub const fn label(self) -> &'static str {
        match self {
            Self::Albedo => "Albedo",
            Self::Normal => "Normal",
            Self::Orm => "ORM",
        }
    }

    const fn color_space(self) -> TextureColorSpace {
        match self {
            Self::Albedo => TextureColorSpace::Srgb,
            Self::Normal | Self::Orm => TextureColorSpace::Linear,
        }
    }
}

/// Complete plaster PBR texture set.
#[derive(Debug, Clone, Eq, PartialEq)]
pub struct PlasterTextureSet {
    /// Base color texture.
    pub albedo: GeneratedTexture,
    /// Tangent-space normal map.
    pub normal: GeneratedTexture,
    /// Occlusion, roughness, metallic packed texture.
    pub orm: GeneratedTexture,
}

/// Samples the procedural plaster height field.
#[must_use]
pub fn plaster_height(params: &PlasterParams, u: f32, v: f32) -> f32 {
    let h = &params.height;
    let broad = fbm(11 ^ params.seed, h.broad_freq, h.broad_oct, u, v) * h.broad_amp;
    let fine = fbm(12 ^ params.seed, h.fine_freq, h.fine_oct, u, v) * h.fine_amp;
    let patches = fbm(
        13 ^ params.seed,
        h.patches_freq,
        h.patches_oct,
        u + h.patches_u_off,
        v - h.patches_v_off,
    ) * h.patches_amp;
    let pits = speckle(18 ^ params.seed, h.pits_scale, h.pits_threshold, u, v) * h.pits_amp;
    let hair = hairline(
        19 ^ params.seed,
        h.hair_freq,
        h.hair_width,
        u + broad * h.hair_warp,
        v - broad * h.hair_warp,
    ) * h.hair_amp;
    (broad + fine + patches + pits + hair).clamp(0.0, 1.0)
}

/// Generates one plaster PBR texture channel.
#[must_use]
pub fn generate_plaster_channel(
    params: &PlasterParams,
    kind: TextureKind,
    size: TextureSize,
) -> GeneratedTexture {
    let data = match kind {
        TextureKind::Albedo => plaster_albedo(params, size),
        TextureKind::Normal => plaster_normal(params, size),
        TextureKind::Orm => plaster_orm(params, size),
    };

    GeneratedTexture {
        width: size.width,
        height: size.height,
        data,
        color_space: kind.color_space(),
    }
}

/// Generates all plaster PBR texture channels.
#[must_use]
pub fn generate_plaster_set(params: &PlasterParams, size: TextureSize) -> PlasterTextureSet {
    PlasterTextureSet {
        albedo: generate_plaster_channel(params, TextureKind::Albedo, size),
        normal: generate_plaster_channel(params, TextureKind::Normal, size),
        orm: generate_plaster_channel(params, TextureKind::Orm, size),
    }
}

fn plaster_albedo(params: &PlasterParams, size: TextureSize) -> Vec<u8> {
    let seed = params.seed;
    let shade = &params.albedo.shade;
    let tint = &params.albedo.tint;
    build_albedo(
        size,
        params.albedo.base_color,
        |u, v| {
            let broad = fbm(
                14 ^ seed,
                shade.broad_freq,
                shade.broad_oct,
                u * shade.broad_scale + shade.broad_u_off,
                v * shade.broad_scale + shade.broad_v_off,
            );
            let stains = fbm(
                15 ^ seed,
                shade.stains_freq,
                shade.stains_oct,
                u + broad * shade.stains_warp,
                v,
            );
            let streaks = fbm(
                16 ^ seed,
                shade.streaks_freq,
                shade.streaks_oct,
                u * shade.streaks_u_scale,
                v * shade.streaks_v_scale,
            );
            let pores = speckle(
                20 ^ seed,
                shade.pores_scale,
                shade.pores_threshold,
                u + broad * shade.pores_warp,
                v,
            );
            let pale_sand = speckle(
                21 ^ seed,
                shade.pale_sand_scale,
                shade.pale_sand_threshold,
                u - shade.pale_sand_u_off.abs(),
                v + shade.pale_sand_v_off,
            );
            let hair_cracks = hairline(
                22 ^ seed,
                shade.hair_freq,
                shade.hair_width,
                u * shade.hair_u_scale + broad * shade.hair_warp_scale,
                v * shade.hair_v_scale,
            );
            let vertical = (1.0 - v.fract()).powf(shade.vertical_exp) * shade.vertical_amp;
            let height_val = plaster_height(params, u, v);
            let base = shade.shade_base
                + height_val * (1.0 - shade.shade_base)
                + broad * shade.shade_broad_amp
                - stains * shade.shade_stains_amp
                - streaks * vertical * shade.shade_streaks_amp
                - pores * shade.shade_pores_amp
                + pale_sand * shade.shade_pale_amp
                - hair_cracks.powf(2.0) * shade.shade_hair_amp;
            base.clamp(shade.shade_min, shade.shade_max)
        },
        |u, v| {
            let age = fbm(
                17 ^ seed,
                tint.age_freq,
                tint.age_oct,
                u - tint.age_u_off.abs(),
                v + tint.age_v_off,
            );
            [
                tint.base_r + age * tint.age_r_amp,
                tint.base_g + age * tint.age_g_amp,
                tint.base_b + age * tint.age_b_amp,
            ]
        },
    )
}

fn plaster_normal(params: &PlasterParams, size: TextureSize) -> Vec<u8> {
    build_normal(
        size,
        |u, v| plaster_height(params, u, v),
        params.normal.strength,
    )
}

fn plaster_orm(params: &PlasterParams, size: TextureSize) -> Vec<u8> {
    let orm = &params.orm;
    build_orm(
        size,
        |u, v| {
            let height = plaster_height(params, u, v);
            orm.ao_base + height * orm.ao_height_amp
        },
        |u, v| {
            let height = plaster_height(params, u, v);
            orm.rough_base + height * orm.rough_height_amp
        },
        |_, _| 0.0,
    )
}
